include:
  - project: 'docker/deploy/deploy-templates'
    file:
      - 'yaml/.gitlab-ci-set-variables.yml'
      - 'yaml/.gitlab-ci-build.yml'
      - 'yaml/.gitlab-ci-deploy.yml'

stages:
  - set-variables
  - build
  - deploy

build:
  script:
    - !reference [ .pull-build-image ]
    - >
      docker build
      -f Dockerfile.bot
      -t ${CI_REGISTRY_IMAGE}/build:${TAG}
      --cache-from ${CI_REGISTRY_IMAGE}/build:${TAG} 
      --target build-env
      --build-arg ENVIRONMENT=${ENVIRONMENT}
      .
    - !reference [ .push-build-image ]
    - !reference [ .pull-tag-image ]
    - >
      docker build 
      -f Dockerfile.bot
      -t ${CI_REGISTRY_IMAGE}:${TAG}
      --cache-from ${CI_REGISTRY_IMAGE}:${TAG}
      --cache-from ${CI_REGISTRY_IMAGE}/build:${TAG}  
      --build-arg ENVIRONMENT=${ENVIRONMENT}
      .
    - !reference [ .push-tag-image ]

    - docker pull ${CI_REGISTRY_IMAGE}/build:${TAG}-web || true
    - >
      docker build
      -f Dockerfile.web
      -t ${CI_REGISTRY_IMAGE}/build:${TAG}-web
      --cache-from ${CI_REGISTRY_IMAGE}/build:${TAG}-web 
      --build-arg ENVIRONMENT=${ENVIRONMENT}
      --target build-env
      .
    - docker push ${CI_REGISTRY_IMAGE}/build:${TAG}-web

    - docker pull ${CI_REGISTRY_IMAGE}:${TAG}-web || true
    - >
      docker build 
      -f Dockerfile.web
      -t ${CI_REGISTRY_IMAGE}:${TAG}-web
      --cache-from ${CI_REGISTRY_IMAGE}:${TAG}-web
      --cache-from ${CI_REGISTRY_IMAGE}/build:${TAG}-web  
      --build-arg ENVIRONMENT=${ENVIRONMENT}
      .
    - docker push ${CI_REGISTRY_IMAGE}:${TAG}-web

    - docker pull ${CI_REGISTRY_IMAGE}/build:${TAG}-scheduler || true
    - >
      docker build
      -f Dockerfile.scheduler
      -t ${CI_REGISTRY_IMAGE}/build:${TAG}-scheduler
      --cache-from ${CI_REGISTRY_IMAGE}/build:${TAG}-scheduler 
      --target build-env
      .
    - docker push ${CI_REGISTRY_IMAGE}/build:${TAG}-scheduler

    - docker pull ${CI_REGISTRY_IMAGE}:${TAG}-scheduler || true
    - >
      docker build 
      -f Dockerfile.scheduler
      -t ${CI_REGISTRY_IMAGE}:${TAG}-scheduler
      --cache-from ${CI_REGISTRY_IMAGE}:${TAG}-scheduler
      --cache-from ${CI_REGISTRY_IMAGE}/build:${TAG}-scheduler  
      .
    - docker push ${CI_REGISTRY_IMAGE}:${TAG}-scheduler
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
      exists:
        - Dockerfile.web
        - Dockerfile.bot
        - Dockerfile.scheduler


deploy:
  script:
    - ssh -p $SSH_PORT $SSH_ADDR "cd ${PROJECT_DIR} && docker-compose stop ${CONTAINER_SERVICE} ${CONTAINER_SERVICE}-web ${CONTAINER_SERVICE}-scheduler && docker-compose rm -f ${CONTAINER_SERVICE} ${CONTAINER_SERVICE}-web ${CONTAINER_SERVICE}-scheduler && docker-compose pull ${CONTAINER_SERVICE} ${CONTAINER_SERVICE}-web ${CONTAINER_SERVICE}-scheduler && docker-compose up -d ${CONTAINER_SERVICE} ${CONTAINER_SERVICE}-web ${CONTAINER_SERVICE}-scheduler && exit"
  rules:
   - if: $CI_COMMIT_BRANCH == "dev"