# Stage 1: Build Frontend
# Use a Node.js image to build the frontend assets
FROM node:20-alpine as build-env

# Install git
RUN apk add --no-cache git

# Create a temporary directory for the entire project source and set it as working directory.
# This directory will hold a copy of your local Git repository.
WORKDIR /usr/src/app/repo_source

# Copy the entire build context (your local project directory, including its .git folder)
# into this stage.
COPY ./front/ .

# Install frontend dependencies and build the project.
# This assumes package.json is at the root of the checked-out branch
# and 'dist' is the output folder.
RUN npm install --force
RUN npm run build:dev

# Stage 2: Build Flask Application
# Use a Python runtime as the base for the final application image
FROM python:3.9-slim-bullseye

# Set the working directory in the container
WORKDIR /app

# Install system dependencies required for building some Python packages (e.g., gevent)
# and for MySQL client libraries
RUN apt-get update && apt-get install -y \
    build-essential \
    default-libmysqlclient-dev \
    gcc \
    netcat-traditional \
    && rm -rf /var/lib/apt/lists/*

# Copy local requirements.txt and install Python dependencies
COPY back/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the built frontend assets from the frontend_builder stage.
# The 'dist' folder is now expected to be located inside /usr/src/app/repo_source/dist.
COPY --from=build-env /usr/src/app/repo_source/dist /app/app/static

# Set permissions for the static folder recursively
RUN chmod -R 775 /app/app/static

# Copy the rest of the Flask application code (app/ directory)
COPY back/app /app/app

# ADD THIS LINE TO COPY THE MIGRATIONS FOLDER
# This copies 'back/migrations' from your host into '/app/migrations' in the container.
COPY back/migrations /app/migrations

# Expose port 8011, where Gunicorn will listen
EXPOSE 8011

# Copy the entrypoint script from the new 'back' folder
# Change the destination to something like /usr/local/bin/ or directly /entrypoint_web.sh
# to ensure it's in the PATH, or directly reference it in ENTRYPOINT.
COPY back/entrypoint_web.sh /usr/local/bin/entrypoint_web.sh
RUN chmod +x /usr/local/bin/entrypoint_web.sh

ENTRYPOINT ["entrypoint_web.sh"]
