# Dockerfile.scheduler
FROM python:3.9-slim-buster as build-env

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    default-libmysqlclient-dev \
    gcc \
    netcat-traditional \
    && rm -rf /var/lib/apt/lists/*

# Copy requirements.txt and install Python dependencies
COPY back/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Install APScheduler
RUN pip install --no-cache-dir apscheduler

# Copy .env and the Flask application code
COPY back/app /app/app
COPY back/app/scheduler.py /app/scheduler.py
COPY back/scripts/run_sync_once.py /app/run_sync_once.py
COPY back/scripts/print_db_data.py /app/print_db_data.py
COPY back/scripts/drop_db_tables.py /app/drop_db_tables.py

# Copy the entrypoint script from the new 'back' folder
COPY back/entrypoint_scheduler.sh /usr/local/bin/entrypoint_scheduler.sh
RUN chmod +x /usr/local/bin/entrypoint_scheduler.sh

# Command to run the scheduler script (CMD remains the same relative path in container)
ENTRYPOINT ["entrypoint_scheduler.sh"]
