"""Initial schema and product main_category_id

Revision ID: 37c2ceb25c8d
Revises: 
Create Date: 2025-07-08 09:25:06.560068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37c2ceb25c8d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addon',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('iiko_addon_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iiko_addon_id')
    )
    op.create_table('main_category',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('color', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=True),
    sa.Column('iiko_category_ids', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('order',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('delivery_address', sa.String(length=255), nullable=False),
    sa.Column('delivery_phone', sa.String(length=50), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('estimated_delivery', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendation',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('iiko_recommendation_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iiko_recommendation_id')
    )
    op.create_table('category',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('iiko_category_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('color', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=True),
    sa.Column('main_category_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['main_category_id'], ['main_category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iiko_category_id')
    )
    op.create_table('product',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('iiko_product_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('categoryId', sa.String(length=36), nullable=False),
    sa.Column('main_category_id', sa.String(length=36), nullable=True),
    sa.Column('nutrition', sa.JSON(), nullable=True),
    sa.Column('ingredients', sa.JSON(), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('sku', sa.String(length=50), nullable=True),
    sa.Column('measure_unit', sa.String(length=50), nullable=True),
    sa.Column('item_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['categoryId'], ['category.id'], ),
    sa.ForeignKeyConstraint(['main_category_id'], ['main_category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iiko_product_id')
    )
    op.create_table('order_item',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price_at_order', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('selected_addons_ids', sa.JSON(), nullable=True),
    sa.Column('selected_recommendation_ids', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_addon',
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('addon_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['addon_id'], ['addon.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'addon_id')
    )
    op.create_table('product_recommendation',
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('recommendation_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendation.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'recommendation_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_recommendation')
    op.drop_table('product_addon')
    op.drop_table('order_item')
    op.drop_table('product')
    op.drop_table('category')
    op.drop_table('recommendation')
    op.drop_table('order')
    op.drop_table('main_category')
    op.drop_table('addon')
    # ### end Alembic commands ###
