"""Ensure main categories are in exact order

Revision ID: 41a5460c6028
Revises: e6e66f85649d
Create Date: 2025-07-08 22:11:15.326722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41a5460c6028'
down_revision = 'e6e66f85649d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('main_category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_order', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('main_category', schema=None) as batch_op:
        batch_op.drop_column('display_order')

    # ### end Alembic commands ###
