"""Update Order model

Revision ID: 00ef06fa8e9d
Revises: 44796dc079fb
Create Date: 2025-07-17 16:21:46.498432

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '00ef06fa8e9d'
down_revision = '44796dc079fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=50),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.drop_column('delivery_address')
        batch_op.drop_column('delivery_phone')
        batch_op.drop_column('comment')
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', mysql.VARCHAR(collation='utf8mb4_bin', length=50), nullable=False))
        batch_op.add_column(sa.Column('comment', mysql.TEXT(collation='utf8mb4_bin'), nullable=True))
        batch_op.add_column(sa.Column('delivery_phone', mysql.VARCHAR(collation='utf8mb4_bin', length=50), nullable=False))
        batch_op.add_column(sa.Column('delivery_address', mysql.VARCHAR(collation='utf8mb4_bin', length=255), nullable=False))
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=50),
               nullable=True)

    # ### end Alembic commands ###
