"""Add more fields to DeliveryInfo

Revision ID: 0c9c7bb5ef9d
Revises: f9b0c208afcc
Create Date: 2025-07-23 17:44:36.234442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c9c7bb5ef9d'
down_revision = 'f9b0c208afcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('street_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('house_number', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_info', schema=None) as batch_op:
        batch_op.drop_column('house_number')
        batch_op.drop_column('street_name')

    # ### end Alembic commands ###
