"""Add city name to DeliveryInfo

Revision ID: 1ee226872ae9
Revises: 0c9c7bb5ef9d
Create Date: 2025-08-01 00:52:08.737428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ee226872ae9'
down_revision = '0c9c7bb5ef9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_info', schema=None) as batch_op:
        batch_op.drop_column('city_name')

    # ### end Alembic commands ###
