"""Add selected_addons_data/selected_recommendation_data to OrderItem

Revision ID: 2aad3acb8612
Revises: 42f9432667d6
Create Date: 2025-08-12 13:15:40.020625

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2aad3acb8612'
down_revision = '42f9432667d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected_addons_data', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('selected_recommendation_data', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('custom_wok_data', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('custom_price', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('custom_name', sa.String(length=255), nullable=True))
        batch_op.alter_column('product_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=36),
               nullable=True)
        batch_op.drop_column('selected_addons_ids')
        batch_op.drop_column('selected_recommendation_ids')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected_recommendation_ids', mysql.JSON(), nullable=True))
        batch_op.add_column(sa.Column('selected_addons_ids', mysql.JSON(), nullable=True))
        batch_op.alter_column('product_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_bin', length=36),
               nullable=False)
        batch_op.drop_column('custom_name')
        batch_op.drop_column('custom_price')
        batch_op.drop_column('custom_wok_data')
        batch_op.drop_column('selected_recommendation_data')
        batch_op.drop_column('selected_addons_data')

    # ### end Alembic commands ###
