"""Add delivery price to DeliveryInfo

Revision ID: 42f9432667d6
Revises: 1ee226872ae9
Create Date: 2025-08-05 15:52:24.176136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42f9432667d6'
down_revision = '1ee226872ae9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_price', sa.Numeric(precision=10, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_info', schema=None) as batch_op:
        batch_op.drop_column('delivery_price')

    # ### end Alembic commands ###
