"""Add addon group name

Revision ID: 44796dc079fb
Revises: e70d67ee8fd5
Create Date: 2025-07-12 00:43:48.052185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44796dc079fb'
down_revision = 'e70d67ee8fd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_name', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addon', schema=None) as batch_op:
        batch_op.drop_column('group_name')

    # ### end Alembic commands ###
