"""Add user id and display_status fields to Order

Revision ID: 70c54a9242ad
Revises: dc4800377ce5
Create Date: 2025-07-23 13:41:34.190256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70c54a9242ad'
down_revision = 'dc4800377ce5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('display_status', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('display_status')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
