"""Add manual addons to cartItem

Revision ID: 968a7ca59641
Revises: d052c655f9af
Create Date: 2025-10-09 15:05:34.099000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '968a7ca59641'
down_revision = 'd052c655f9af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manual_addons_data', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.drop_column('manual_addons_data')

    # ### end Alembic commands ###
