"""Add Yookassa payment fields to Order

Revision ID: dc4800377ce5
Revises: 00ef06fa8e9d
Create Date: 2025-07-18 10:36:27.459870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc4800377ce5'
down_revision = '00ef06fa8e9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('yookassa_payment_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('confirmation_url', sa.String(length=500), nullable=True))
        batch_op.create_unique_constraint(None, ['yookassa_payment_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('confirmation_url')
        batch_op.drop_column('yookassa_payment_id')

    # ### end Alembic commands ###
