"""Add postcode field to DeliveryInfo

Revision ID: f9b0c208afcc
Revises: 70c54a9242ad
Create Date: 2025-07-23 16:06:30.713049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9b0c208afcc'
down_revision = '70c54a9242ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('postcode', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_info', schema=None) as batch_op:
        batch_op.drop_column('postcode')

    # ### end Alembic commands ###
